<!DOCTYPE html><html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="chrome=1"><title>SublimePeek | Help for throw</title><link href="css/bootstrap.min.css" rel="stylesheet"><style type="text/css">  body {  padding-top: 10px;  padding-bottom: 20px;  padding-left: 10%;  padding-right: 10%;  }  .sidebar-nav {  padding: 9px 0;  }</style><link href="css/bootstrap-responsive.min.css" rel="stylesheet"><link href="css/custom.css" rel="stylesheet">  </head><body><div style="display: block; "><div id="4eea835f8cd2963cba000002" class="page-header"><h2>throw</h2><!--CONTENT--><div id = "section_1"><span id = "Summary"></span><h3 class = "editable">Summary</h3><p>Throws a user-defined exception.</p><table class = "fullwidth-table"> <tbody> <tr> <td class = "header" colspan = "2">Statement</td> </tr> <tr> <td>Implemented in:</td> <td>JavaScript 1.4</td> </tr> <tr> <td>ECMA Version:</td> <td>ECMA-262, Edition 3</td> </tr> </tbody></table></div><div id = "section_2"><span id = "Syntax"></span><h3 class = "editable">Syntax</h3><p><code>throw <em>expression</em>; </code></p></div><div id = "section_3"><span id = "Parameters"></span><h3 class = "editable">Parameters</h3><dl> <dt><code>expression</code></dt> <dd>The expression to throw.</dd></dl></div><div id = "section_4"><span id = "Description"></span><h3 class = "editable">Description</h3><p>Use the <code>throw</code> statement to throw an exception. When you throw an exception, <code>expression</code> specifies the value of the exception. Each of the following throws an exception:</p><ul> <li><code>throw &quot;Error2&quot;; // generates an exception with a string value</code></li> <li><code>throw 42; // generates an exception with the value 42</code></li> <li><code>throw true; // generates an exception with the value true</code></li></ul></div><div id = "section_5"><span id = "Examples"></span><h3 class = "editable">Examples</h3><div id = "section_6"><span id = "Example:_Throw_an_object"></span><h4 class = "editable">Example: Throw an object</h4><p>You can specify an object when you throw an exception. You can then reference the object's properties in the <code>catch</code> block. The following example creates an object <code>myUserException</code> of type <code>UserException</code> and uses it in a <code>throw</code> statement.</p><pre>function UserException(message) {   this.message = message;   this.name = &quot;UserException&quot;;}function getMonthName(mo) {   mo = mo-1; // Adjust month number for array index (1=Jan, 12=Dec)   var months = new Array(&quot;Jan&quot;, &quot;Feb&quot;, &quot;Mar&quot;, &quot;Apr&quot;, &quot;May&quot;, &quot;Jun&quot;, &quot;Jul&quot;,      &quot;Aug&quot;, &quot;Sep&quot;, &quot;Oct&quot;, &quot;Nov&quot;, &quot;Dec&quot;);   if (months[mo]&nbsp;!== undefined) {      return months[mo];   } else {      myUserException = new UserException(&quot;InvalidMonthNo&quot;);      throw myUserException;   }}try {   // statements to try   var myMonth = 15; // 15 is out of bound to raise the exception   monthName = getMonthName(myMonth);} catch (e) {   monthName = &quot;unknown&quot;;   logMyErrors(e.message, e.name); // pass exception object to err handler}</pre></div><div id = "section_7"><span id = "Example:_Another_example_of_throwing_an_object"></span><h4 class = "editable">Example: Another example of throwing an object</h4><p>The following example tests an input string for a U.S. zip code. If the zip code uses an invalid format, the throw statement throws an exception by creating an object of type <code>ZipCodeFormatException</code>.</p><pre>/* * Creates a ZipCode object. * * Accepted formats for a zip code are: *    12345 *    12345-6789 *    123456789 *    12345 6789 * * If the argument passed to the ZipCode constructor does not * conform to one of these patterns, an exception is thrown. */function ZipCode(zip) {   zip = new String(zip);   pattern = /[0-9]{5}([- ]?[0-9]{4})?/;   if (pattern.test(zip)) {      // zip code value will be the first match in the string      this.value = zip.match(pattern)[0];      this.valueOf = function() {         return this.value      };      this.toString = function() {         return String(this.value)      };   } else {      throw new ZipCodeFormatException(zip);   }}function ZipCodeFormatException(value) {   this.value = value;   this.message = &quot;does not conform to the expected format for a zip code&quot;;   this.toString = function() {      return this.value + this.message   };}/* * This could be in a script that validates address data * for US addresses. */var ZIPCODE_INVALID = -1;var ZIPCODE_UNKNOWN_ERROR = -2;function verifyZipCode(z) {   try {      z = new ZipCode(z);   } catch (e) {      if (e instanceof ZipCodeFormatException) {         return ZIPCODE_INVALID;      } else {         return ZIPCODE_UNKNOWN_ERROR;      }   }   return z;}a = verifyZipCode(95060);         // returns 95060b = verifyZipCode(9560;)          // returns -1c = verifyZipCode(&quot;a&quot;);           // returns -1d = verifyZipCode(&quot;95060&quot;);       // returns 95060e = verifyZipCode(&quot;95060 1234&quot;);  // returns 95060 1234</pre></div><div id = "section_8"><span id = "Example:_Rethrow_an_exception"></span><h4 class = "editable">Example: Rethrow an exception</h4><p>You can use <code>throw</code> to rethrow an exception after you catch it. The following example catches an exception with a numeric value and rethrows it if the value is over 50. The rethrown exception propagates up to the enclosing function or to the top level so that the user sees it.</p><pre class = "eval">try {   throw n; // throws an exception with a numeric value} catch (e) {   if (e &lt;= 50) {      // statements to handle exceptions 1-50   } else {      // cannot handle this exception, so rethrow      throw e;   }}</pre></div></div><div id = "section_6"><span id = "Example:_Throw_an_object"></span><h4 class = "editable">Example: Throw an object</h4><p>You can specify an object when you throw an exception. You can then reference the object's properties in the <code>catch</code> block. The following example creates an object <code>myUserException</code> of type <code>UserException</code> and uses it in a <code>throw</code> statement.</p><pre>function UserException(message) {   this.message = message;   this.name = &quot;UserException&quot;;}function getMonthName(mo) {   mo = mo-1; // Adjust month number for array index (1=Jan, 12=Dec)   var months = new Array(&quot;Jan&quot;, &quot;Feb&quot;, &quot;Mar&quot;, &quot;Apr&quot;, &quot;May&quot;, &quot;Jun&quot;, &quot;Jul&quot;,      &quot;Aug&quot;, &quot;Sep&quot;, &quot;Oct&quot;, &quot;Nov&quot;, &quot;Dec&quot;);   if (months[mo]&nbsp;!== undefined) {      return months[mo];   } else {      myUserException = new UserException(&quot;InvalidMonthNo&quot;);      throw myUserException;   }}try {   // statements to try   var myMonth = 15; // 15 is out of bound to raise the exception   monthName = getMonthName(myMonth);} catch (e) {   monthName = &quot;unknown&quot;;   logMyErrors(e.message, e.name); // pass exception object to err handler}</pre></div><div id = "section_7"><span id = "Example:_Another_example_of_throwing_an_object"></span><h4 class = "editable">Example: Another example of throwing an object</h4><p>The following example tests an input string for a U.S. zip code. If the zip code uses an invalid format, the throw statement throws an exception by creating an object of type <code>ZipCodeFormatException</code>.</p><pre>/* * Creates a ZipCode object. * * Accepted formats for a zip code are: *    12345 *    12345-6789 *    123456789 *    12345 6789 * * If the argument passed to the ZipCode constructor does not * conform to one of these patterns, an exception is thrown. */function ZipCode(zip) {   zip = new String(zip);   pattern = /[0-9]{5}([- ]?[0-9]{4})?/;   if (pattern.test(zip)) {      // zip code value will be the first match in the string      this.value = zip.match(pattern)[0];      this.valueOf = function() {         return this.value      };      this.toString = function() {         return String(this.value)      };   } else {      throw new ZipCodeFormatException(zip);   }}function ZipCodeFormatException(value) {   this.value = value;   this.message = &quot;does not conform to the expected format for a zip code&quot;;   this.toString = function() {      return this.value + this.message   };}/* * This could be in a script that validates address data * for US addresses. */var ZIPCODE_INVALID = -1;var ZIPCODE_UNKNOWN_ERROR = -2;function verifyZipCode(z) {   try {      z = new ZipCode(z);   } catch (e) {      if (e instanceof ZipCodeFormatException) {         return ZIPCODE_INVALID;      } else {         return ZIPCODE_UNKNOWN_ERROR;      }   }   return z;}a = verifyZipCode(95060);         // returns 95060b = verifyZipCode(9560;)          // returns -1c = verifyZipCode(&quot;a&quot;);           // returns -1d = verifyZipCode(&quot;95060&quot;);       // returns 95060e = verifyZipCode(&quot;95060 1234&quot;);  // returns 95060 1234</pre></div><div id = "section_8"><span id = "Example:_Rethrow_an_exception"></span><h4 class = "editable">Example: Rethrow an exception</h4><p>You can use <code>throw</code> to rethrow an exception after you catch it. The following example catches an exception with a numeric value and rethrows it if the value is over 50. The rethrown exception propagates up to the enclosing function or to the top level so that the user sees it.</p><pre class = "eval">try {   throw n; // throws an exception with a numeric value} catch (e) {   if (e &lt;= 50) {      // statements to handle exceptions 1-50   } else {      // cannot handle this exception, so rethrow      throw e;   }}</pre></div><div id = "section_9"><span id = "See_also"></span><h3 class = "editable">See also</h3><p><a title = "en/JavaScript/Reference/Statements/try...catch" rel = "internal" href = "https://developer.mozilla.org/en/JavaScript/Reference/Statements/try...catch">try...catch</a></p><p>&nbsp;</p><p>&nbsp;</p><p></p></div><!--NOTE--><p class="source-link">This content was sourced by <a href="http://dochub.io/">DocHub</a> from MDN.</p></div></div></body></html>